### ISSUE TITLE
[EPIC] - Host Dqualizer on AWS

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqualizer#36]
## Rationale
To make it easier to setup Dqualizer for demonstration, we want to host dqualizer on AWS.

## Owner
Novatec

## Acceptance criteria
- [ ] There are Helm Charts to Deploy Dqualizer
- [ ] There are some People who know how to set it up and manage it on AWS
- [ ] There is a Documentation, how to set it up in an EKS
